### ISSUE TITLE
当前已经放行了云备份？

### ISSUE THREAD

**Issue by Stop-586** [lingeringsound/10007#10]
在模块182/183/184，可能这个云备份还是卡进度，然后提示网络异常。他这个备份是分为小米备份，小米云备份，以及小米云服务。小米备份是刷机时备份数据的。而桌面备份指向云备份和云服务，两个必须打开，缺一则无法运行云备份。不知道作者在184当前放行了的是不是云备份和云服务。如果是，那就是我自己的问题，也许是网络不好。谢谢作者的付出！

**Comment by yuexps** [comment]
我也是，小米云备份网络错误
放行了a0.app.xiaomi.com的
![Screenshot_2024-11-02-06-58-14-921_me weishu kernelsu](https://github.com/user-attachments/assets/2ef709d9-b0d6-4d7b-bd43-316077ddf420)

**Comment by lingeringsound** [comment]
感谢反馈，不好意思，年纪大了，把代码写反了😭，184的禁用实际上是启用，185已经修了，试试吧。

**Comment by lingeringsound** [comment]
> 我也是，小米云备份网络错误 放行了a0.app.xiaomi.com的 ![Screenshot_2024-11-02-06-58-14-921_me weishu kernelsu](https://private-user-images.githubusercontent.com/69074603/382422618-2ef709d9-b0d6-4d7b-bd43-316077ddf420.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MTk0NzMsIm5iZiI6MTczMDUxOTE3MywicGF0aCI6Ii82OTA3NDYwMy8zODI0MjI2MTgtMmVmNzA5ZDktYjBkNi00ZDdiLWJkNDMtMzE2MDc3ZGRmNDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDAzNDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxODdmMmRmYjNiOTc2NjhkYzFiMGE1MDg0ODI0MjQzNmVkZDIwNzI3ZjQ0ZTZhMTdiOTc3ZWVhNWRiZmFlYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MI5eTO3U01_jgDbikP747yXQvAi8OBNReQLxk1AMOSg)

实际上是我写反了，不好意思。

**Comment by Stop-586** [comment]
明白了，谢谢作者！

**Comment by scwlwj** [comment]
明白了，谢谢作者！

**Comment by yuexps** [comment]
> > 我也是，小米云备份网络错误 放行了a0.app.xiaomi.com的 ![Screenshot_2024-11-02-06-58-14-921_me weishu kernelsu](https://private-user-images.githubusercontent.com/69074603/382422618-2ef709d9-b0d6-4d7b-bd43-316077ddf420.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MTk0NzMsIm5iZiI6MTczMDUxOTE3MywicGF0aCI6Ii82OTA3NDYwMy8zODI0MjI2MTgtMmVmNzA5ZDktYjBkNi00ZDdiLWJkNDMtMzE2MDc3ZGRmNDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDAzNDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxODdmMmRmYjNiOTc2NjhkYzFiMGE1MDg0ODI0MjQzNmVkZDIwNzI3ZjQ0ZTZhMTdiOTc3ZWVhNWRiZmFlYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MI5eTO3U01_jgDbikP747yXQvAi8OBNReQLxk1AMOSg)
> 
> 实际上是我写反了，不好意思。

好的，能用了

**Comment by scwlwj** [comment]
我这还是不行，错误依然存在。用的 Hyper OS2

**Comment by yuexps** [comment]
> 我这还是不行，错误依然存在。用的 Hyper OS2

执行action没，如果不行就去改下这个文件试试
![Screenshot_2024-11-02-15-28-23-943_bin mt plus](https://github.com/user-attachments/assets/0581d5e2-1831-4a78-ac35-d79a60a3423a)

**Comment by scwlwj** [comment]
> > 我这还是不行，错误依然存在。用的 Hyper OS2
> 
> 执行action没，如果不行就去改下这个文件试试 ![Screenshot_2024-11-02-15-28-23-943_bin mt plus](https://private-user-images.githubusercontent.com/69074603/382456029-0581d5e2-1831-4a78-ac35-d79a60a3423a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDI3NDgsIm5iZiI6MTczMDYwMjQ0OCwicGF0aCI6Ii82OTA3NDYwMy8zODI0NTYwMjktMDU4MWQ1ZTItMTgzMS00YTc4LWFjMzUtZDc5YTYwYTM0MjNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDAyNTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZTc0MzEzM2IyMjYyYzQxOWJlZjRlOTBkMWNkNWI5ODc2YzcwZWYzNWE2MGNkY2IyZWU1OWIwZTI5OWNmYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uIizC3ORKBbUBzAFrmVOHOIdkZA_PfPTkqi_YR6f6Bk)

执行action没用，通过修改截图中的文件可以了。感谢🙏

**Comment by Spectrollay** [comment]
> > 我这还是不行，错误依然存在。用的 Hyper OS2
> 
> 执行action没，如果不行就去改下这个文件试试 ![Screenshot_2024-11-02-15-28-23-943_bin mt plus](https://private-user-images.githubusercontent.com/69074603/382456029-0581d5e2-1831-4a78-ac35-d79a60a3423a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzcwNzQsIm5iZiI6MTczMDYzNjc3NCwicGF0aCI6Ii82OTA3NDYwMy8zODI0NTYwMjktMDU4MWQ1ZTItMTgzMS00YTc4LWFjMzUtZDc5YTYwYTM0MjNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEyMjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhY2Q3ZGEzMGFlZDMwNmU0MGQyZDc1YzNjMjg0ZTVhMzY2MjczMzVjNjkzZmE0MmRmZGQxZWYxOGQ1ODRjODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gzreoL5Za1KfMLQHYvd03HdzL3SuNcu_Jdcbq2K8FQU)

修改文件下次更新会被覆盖吗,还是会被保留为自定义规则

**Comment by EndesrDragons** [comment]
在最新的186版本里，云备份还是存在问题，在小米13ultra里，系统版本1.0.17，云备份进度条始终处于百分之五，确实还存在一些问题，需要大佬看一下是怎么回事

**Comment by EndesrDragons** [comment]
> > 在最新的186版本里，云备份还是存在问题，在小米13ultra里，系统版本1.0.17，云备份进度条始终处于百分之五，确实还存在一些问题，需要大佬看一下是怎么回事
> 
> 你改过模块路径里的那个文件了没？改一下再试试

怎么改，我找到哪个文件夹里的文件了

**Comment by Stop-586** [comment]
> > > 在最新的186版本里，云备份还是存在问题，在小米13ultra里，系统版本1.0.17，云备份进度条始终处于百分之五，确实还存在一些问题，需要大佬看一下是怎么回事
> > 
> > 你改过模块路径里的那个文件了没？改一下再试试
> 
> 怎么改，我找到哪个文件夹里的文件了
> 

你仔细回看一下议题评论区，作者已经截图了

**Comment by EndesrDragons** [comment]
> > > > 在最新的186版本里，云备份还是存在问题，在小米13ultra里，系统版本1.0.17，云备份进度条始终处于百分之五，确实还存在一些问题，需要大佬看一下是怎么回事
> > > 
> > > 
> > > 你改过模块路径里的那个文件了没？改一下再试试
> > 
> > 
> > 怎么改，我找到哪个文件夹里的文件了
> 
> 你仔细回看一下议题评论区，作者已经截图了，.bak掉就行了

好的，感谢

**Comment by lingeringsound** [comment]
> 在最新的186版本里，云备份还是存在问题，在小米13ultra里，系统版本1.0.17，云备份进度条始终处于百分之五，确实还存在一些问题，需要大佬看一下是怎么回事

- ![Screenshot_2024-11-05-22-19-06-741-edit_k.ye.rhc.q.a.jpg](https://github.com/user-attachments/assets/99dfa76e-db0b-4c27-85db-777ebdc7caaf)

没有点击action(操作)按钮吗？如果没有这个按钮需要到模块路径文件`/data/adb/modules/GGAT_10007/mod/a0.app.xiaomi.com.sh`，修改去掉注释就行，`iptables -A`是添加规则(拦截`a0.app.xiaomi.com`)，`iptables -D`是删除规则(放行`a0.app.xiaomi.com`)。
![Screenshot_2024-11-05-22-21-35-654-edit_bin.mt.plus.jpg](https://github.com/user-attachments/assets/48619b68-ccb3-4acd-a983-d3ffb8096b96)

很奇怪，我这边测试action是没问题的😂……

**Comment by yuexps** [comment]
> > 在最新的186版本里，云备份还是存在问题，在小米13ultra里，系统版本1.0.17，云备份进度条始终处于百分之五，确实还存在一些问题，需要大佬看一下是怎么回事
> 
> * ![Screenshot_2024-11-05-22-19-06-741-edit_k.ye.rhc.q.a.jpg](https://private-user-images.githubusercontent.com/114198798/383182788-99dfa76e-db0b-4c27-85db-777ebdc7caaf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTcxMDYsIm5iZiI6MTczMDgxNjgwNiwicGF0aCI6Ii8xMTQxOTg3OTgvMzgzMTgyNzg4LTk5ZGZhNzZlLWRiMGItNGMyNy04NWRiLTc3N2ViZGM3Y2FhZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNDI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmYyNzgyOGFhNDIyOGJiMWRkNGMyOGJiOWFhNDlkYzQwNzMwNWI5ZmViNzk3ZTZjZTllZTRhYjQyYTM1N2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JPA0axi2jtYrf-_aOJ7qcp_l0eQkv-DJYg5vq7-Bv9Y)
> 
> 没有点击action(操作)按钮吗？如果没有这个按钮需要到模块路径文件`/data/adb/modules/GGAT_10007/mod/a0.app.xiaomi.com.sh`，修改去掉注释就行，`iptables -A`是添加规则(拦截`a0.app.xiaomi.com`)，`iptables -D`是删除规则(放行`a0.app.xiaomi.com`)。 ![Screenshot_2024-11-05-22-21-35-654-edit_bin.mt.plus.jpg](https://private-user-images.githubusercontent.com/114198798/383184187-48619b68-ccb3-4acd-a983-d3ffb8096b96.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTcxMDYsIm5iZiI6MTczMDgxNjgwNiwicGF0aCI6Ii8xMTQxOTg3OTgvMzgzMTg0MTg3LTQ4NjE5YjY4LWNjYjMtNGFjZC1hOTgzLWQzZmZiODA5NmI5Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNDI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDY5MDRlYTUzNGZmMzI4NjdhMWVkNDQ2YWJkODQzODJmZDQ0NWM5N2JiMzlkZmM3Y2IwNDViZDM5YzY1MjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FJdtJ0n2QzboLmX_7cnNvRQB1R5o2FjwwZiH8woPEdw)
> 
> 很奇怪，我这边测试action是没问题的😂……

我使用的kernelSU，执行action后还是无法使用云备份，重启后也不行。
将a0.app.xiaomi.com删掉或注释掉重启后就能用了😂

**Comment by lingeringsound** [comment]
> > > 在最新的186版本里，云备份还是存在问题，在小米13ultra里，系统版本1.0.17，云备份进度条始终处于百分之五，确实还存在一些问题，需要大佬看一下是怎么回事
> > 
> > * ![Screenshot_2024-11-05-22-19-06-741-edit_k.ye.rhc.q.a.jpg](https://private-user-images.githubusercontent.com/114198798/383182788-99dfa76e-db0b-4c27-85db-777ebdc7caaf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTcxMDYsIm5iZiI6MTczMDgxNjgwNiwicGF0aCI6Ii8xMTQxOTg3OTgvMzgzMTgyNzg4LTk5ZGZhNzZlLWRiMGItNGMyNy04NWRiLTc3N2ViZGM3Y2FhZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNDI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmYyNzgyOGFhNDIyOGJiMWRkNGMyOGJiOWFhNDlkYzQwNzMwNWI5ZmViNzk3ZTZjZTllZTRhYjQyYTM1N2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JPA0axi2jtYrf-_aOJ7qcp_l0eQkv-DJYg5vq7-Bv9Y)
> > 
> > 没有点击action(操作)按钮吗？如果没有这个按钮需要到模块路径文件`/data/adb/modules/GGAT_10007/mod/a0.app.xiaomi.com.sh`，修改去掉注释就行，`iptables -A`是添加规则(拦截`a0.app.xiaomi.com`)，`iptables -D`是删除规则(放行`a0.app.xiaomi.com`)。 ![Screenshot_2024-11-05-22-21-35-654-edit_bin.mt.plus.jpg](https://private-user-images.githubusercontent.com/114198798/383184187-48619b68-ccb3-4acd-a983-d3ffb8096b96.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTcxMDYsIm5iZiI6MTczMDgxNjgwNiwicGF0aCI6Ii8xMTQxOTg3OTgvMzgzMTg0MTg3LTQ4NjE5YjY4LWNjYjMtNGFjZC1hOTgzLWQzZmZiODA5NmI5Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNDI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDY5MDRlYTUzNGZmMzI4NjdhMWVkNDQ2YWJkODQzODJmZDQ0NWM5N2JiMzlkZmM3Y2IwNDViZDM5YzY1MjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FJdtJ0n2QzboLmX_7cnNvRQB1R5o2FjwwZiH8woPEdw)
> > 
> > 很奇怪，我这边测试action是没问题的😂……
> 
> 我使用的kernelSU，执行action后还是无法使用云备份，重启后也不行。
> 将a0.app.xiaomi.com删掉或注释掉重启后就能用了😂

`iptables`命令执行无需重启，直接执行脚本就行，不清楚kernelsu`action.sh`和alpha有什么不同，反正我这边是没问题的。
