### ISSUE TITLE
环境异常问题

### ISSUE THREAD

**Issue by Chameng** [lingeringsound/10007#11]
装本模块会被检测软件查出异常 
![Screenshot_2024-11-03-22-38-04-92_4628cdb1cc7e49697dea6a87fb1e9f1b](https://github.com/user-attachments/assets/4c33bf1f-5a90-4eaf-b5bc-b5e5818e64b7)
![IMG_20241103_225249](https://github.com/user-attachments/assets/2b522c59-2eba-4cd1-9ad0-93618f468927)

**Comment by lingeringsound** [comment]
这种问题，别来问我。
