### ISSUE TITLE
coloros无法访问软件商店

### ISSUE THREAD

**Issue by wx40217** [lingeringsound/10007#13]
hosts内有许多oppo规则 是否和这些有关？有需要我可以抓包看一下

**Comment by lingeringsound** [comment]
~~不清楚，我没有OPPO的机子(事实上我已经好久没换手机了，你可以自己抓包，然后放行试试。~~

---

![Screenshot_2024-11-07-23-13-39-127_com.heytap.market.jpg](https://github.com/user-attachments/assets/120f7379-e459-45e0-9bc6-3b4dc40fbee4)

![Screenshot_2024-11-07-23-13-46-696_com.heytap.market.jpg](https://github.com/user-attachments/assets/f4466ae7-2bbf-4d91-987d-0b4bd8b6ddb9)

---

- 下了一个OPPO应用商店，发现能装上，并且无事发生。

**Comment by wx40217** [comment]
已修复 感谢大佬～
