### ISSUE TITLE
无法登陆网易游戏sky光遇官服

### ISSUE THREAD

**Issue by niani2** [lingeringsound/10007#14]
好像是从橴炫v182或者橴炫v183版本就开始无法登录 一直卡在登录界面转圈圈 呜呜呜 关闭模块后又可以登录了🥹🥹🥹

**Comment by lingeringsound** [comment]
不玩游戏，解决不了，你可以尝试自己抓包看看。

**Comment by niani2** [comment]
> 不玩游戏，解决不了，你可以尝试自己抓包看看。

怎么抓呀🥹🥹

**Comment by lingeringsound** [comment]
> > 不玩游戏，解决不了，你可以尝试自己抓包看看。
> 
> 怎么抓呀🥹🥹

下载Adguard，添加我的订阅规则，开启过滤(开小窗)，看过滤日志，看看那个被拦截(红色)，然后自己点击被拦截的规则，一个个放行，看看放行那个规则能登陆，就是那个域名。

**Comment by niani2** [comment]
> 一个

谢谢大佬 🥺🥺😘😘

**Comment by niani2** [comment]
> > > 不玩游戏，解决不了，你可以尝试自己抓包看看。
> > 
> > 怎么抓呀🥹🥹
> 
> 下载Adguard，添加我的订阅规则，开启过滤(开小窗)，看过滤日志，看看那个被拦截(红色)，然后自己点击被拦截的规则，一个个放行，看看放行那个规则能登陆，就是那个域名。

谢谢大佬 找到啦 嘻嘻(#^.^#) 可以登录了 是这条规则127.0.0.1 fp-upload.dun.163.com

**Comment by lingeringsound** [comment]
好的，感谢反馈，辛苦你了！
