### ISSUE TITLE
大佬click.discord.com怎么也给屏蔽了

### ISSUE THREAD

**Issue by Yinhono** [lingeringsound/10007#16]
discord关于账户方面比如新设备验证和重置密码什么的用的不都是这个域名嘛

**Comment by lingeringsound** [comment]
感谢反馈，但是这个你得问上游[7](https://github.com/StevenBlack/hosts/blob/refs%2Fheads%2Fmaster/data%2Fyoyo.org%2Fhosts)，规则是网络抓取+本人手动抓取的，这个规则不是我抓的😂。

**Comment by lingeringsound** [comment]
已经在[193](https://lingeringsound.github.io/10007/module/ads193.zip)中修复，试试看吧。
