### ISSUE TITLE
小米云备份数据恢复被屏蔽

### ISSUE THREAD

**Issue by Say-Hi-bye** [lingeringsound/10007#17]
api.ad.xiaomi.com 会屏蔽云备份数据恢复，一直显示加载中，无法加载数据。删除后正常，能否加入放行，不然每次更新都要手动删除
![IMG_20241110_183140](https://github.com/user-attachments/assets/f9ad74fe-4c22-4340-a225-291307f8610a)

**Comment by Say-Hi-bye** [comment]
是这个域名，我测试过很多次的。

**Comment by lingeringsound** [comment]
好吧，我把这个域名放到`action.sh`了，用iptables拦截了，没有action按钮，可以直接执行`/data/adb/modules/GGAT_10007/action.sh`可反复切换禁用状态，可以用`anywhere`或者`xposed edge`执行命令。
