### ISSUE TITLE
想玩抖音小游戏怎么修改？打不开小程序

### ISSUE THREAD

**Issue by mojian12138** [lingeringsound/10007#19]
我想玩抖音中的小游戏，但是现在抖音里的小游戏点的话，打不开没有任何反应
需要怎么修改可以打开抖音的小程序
如果可以实现，可以玩小游戏，又不用看广告就可以领取奖励就更好了😉

**Comment by lingeringsound** [comment]
好的，感谢反馈，但是……
- ①我不刷抖音😢，所以只能随机等一个大佬抓包。
- ②这个模块只是个简单的magisk模块，应该做不到跳过看广告得广告奖励。

**Comment by lingeringsound** [comment]
> 设置抖音白名单是不是就可以打开抖音的小程序了，现在所有小程序都点不开

- 下了一个，试了一下，小程序正常打开啊，没问题，就是这抖音检测还挺多的，好久没登直接给我封禁了，另外玩意用的是自带的内核`webview_bytedance`，你检查下`zygisk next`或者`shamiko`之类影响webview的东西，还有抖音有没有适配你的安卓版本，毕竟他用的定制内核。

---

> ![Screenshot_2024-11-12-18-00-50-775_com.ss.android.ugc.aweme.jpg](https://github.com/user-attachments/assets/1997ea4e-7d3d-40d3-94f1-8a82ada703c8)

> ![Screenshot_2024-11-12-18-00-40-641_com.ss.android.ugc.aweme.jpg](https://github.com/user-attachments/assets/afd5e180-6222-4e3e-9775-1a7bd8374b2b)

> ![Screenshot_2024-11-12-18-00-46-542_com.ss.android.ugc.aweme.jpg](https://github.com/user-attachments/assets/6bd9c5a1-6b20-4f71-8521-03c44f9d2ff9)
---

**Comment by mojian12138** [comment]
请问怎么可以卸载干净呀？卸载模块后，重启
然后使用adaway把hosts文件还原了，也通过mt管理器检查了，systemless hosts现在也是关的😂
但是现在模块效果依旧存在，广告没有，抖音也打不开
是不是有些文件需要手动删除

**Comment by mojian12138** [comment]
我试了下，抖音升级到最新就可以了
现在注意是想知道怎么卸载干净😂
我想通过systemless hosts方式使用

**Comment by lingeringsound** [comment]
> 我试了下，抖音升级到最新就可以了
> 现在注意是想知道怎么卸载干净😂
> 我想通过systemless hosts方式使用


正常卸载就完事了，有残留就执行`uninstall.sh`，magisk有时候不执行的。
