### ISSUE TITLE
为什么代号9527的就可以去除微信公众号评论上方的视频呢

### ISSUE THREAD

**Issue by 839781960** [lingeringsound/10007#2]

**Comment by lingeringsound** [comment]
因为我没做这方面的屏蔽，做了就会影响小程序的使用，你可以继续订阅 [结界](https://raw.githubusercontent.com/Coolapk-Code9527/-Hosts-/master/system/etc/hosts
) 的Host

**Comment by jiang-yuan** [comment]
> 因为我没做这方面的屏蔽，做了就会影响小程序的使用，你可以继续订阅 [结界](https://raw.githubusercontent.com/Coolapk-Code9527/-Hosts-/master/system/etc/hosts) 的Host

是没有做微信公众号所有广告的屏蔽吗? 我刷了发现微信广告一个没少
有没有不影响小程序又能去公众号文章内广告的方法吗?
