### ISSUE TITLE
api.twitter.com会让推特直接用不了

### ISSUE THREAD

**Issue by yesesou** [lingeringsound/10007#21]
api.twitter.com会让推特直接用不了

**Comment by lingeringsound** [comment]
问题是我根本没拦截这个域名，甚至他还在白名单了。

**Comment by lingeringsound** [comment]
> ![IMG_20241120_194915.jpg](https://github.com/user-attachments/assets/bafa2c37-80c9-4aa2-a9c6-5186be5a31bd)

---

**Comment by yesesou** [comment]
推送更新的也可以了，好奇怪，之前还不行的

**Comment by lingeringsound** [comment]
还是检查下你的代理工具或者订阅的✈吧，现在基本都自带拦截规则。
