### ISSUE TITLE
README.md密码

### ISSUE THREAD

**Issue by Stop-586** [lingeringsound/10007#22]
请问作者202版本README.md查看密码是多少？

**Comment by lingeringsound** [comment]
[更新日志](https://github.com/lingeringsound/10007/blob/main/update.md)

伪加密，无密码，自己用命令行解压或者下载解压软件解压。

**Comment by Stop-586** [comment]
> [更新日志](https://github.com/lingeringsound/10007/blob/main/update.md)
> 
> 伪加密，无密码，自己用命令行解压或者下载解压软件解压。

好的，谢谢
