### ISSUE TITLE
请问最新版的两个模块不支持ksu吗

### ISSUE THREAD

**Issue by kanade521** [lingeringsound/10007#23]
最新版本的202和203ksu刷入失败 201以下就没有问题

**Comment by EndesrDragons** [comment]
需要用其他软件解压吗？zip文件有密码，看到大佬做了伪加密

**Comment by kanade521** [comment]
> 需要用其他软件解压吗？zip文件有密码，看到大佬做了伪加密

搜一下伪加密解密方法就行，github上有个项目，自己手动改也行

**Comment by EndesrDragons** [comment]
> > 需要用其他软件解压吗？zip文件有密码，看到大佬做了伪加密
> 
> 搜一下伪加密解密方法就行，github上有个项目，自己手动改也行
网上找了很多关于伪加密的项目，最终都已失败告终，还有什么更好的方法么

**Comment by guozi1373124875** [comment]
文件加密了吗

**Comment by EndesrDragons** [comment]
> 文件加密了吗

对的，伪加密

**Comment by EndesrDragons** [comment]
> > 需要用其他软件解压吗？zip文件有密码，看到大佬做了伪加密
> 
> 搜一下伪加密解密方法就行，github上有个项目，自己手动改也行

网上找了很多关于伪加密的项目，最终都已失败告终，还有什么更好的方法么
