### ISSUE TITLE
Magisk alpha(26103)刷入模块208失败

### ISSUE THREAD

**Issue by Aloazny** [lingeringsound/10007#24]
- 刷入208失败，203可以正常刷入。
- 不知为何文件路径出现了`//`。
- 抱歉打扰大佬了，希望能大佬有空的时候能修复一下。

![b36f14db54fd0e9573d02ed20451d616.png](https://github.com/user-attachments/assets/17b798f4-98dd-4e6a-ae29-f9b05679fce2)

![f2d72a5904fafaa61a33eb14869fb040.jpeg](https://github.com/user-attachments/assets/00052fac-be86-4569-8cc1-a5291a1b5a7c)

**Comment by lingeringsound** [comment]
好的，感谢反馈，但是有点离谱😱，不应该先提示文件丢失吗？这个路径能存在？

**Comment by lingeringsound** [comment]
更新了，你试试。

**Comment by Aloazny** [comment]
> 更新了，你试试。

好的，谢谢大佬！
