### ISSUE TITLE
作者你好，微信小程序欢乐斗地主无法看广告奖励

### ISSUE THREAD

**Issue by AsuraArthur** [lingeringsound/10007#27]
如题，广告奖励=是，仍然黑屏，无法播放广告获得奖励

**Comment by lingeringsound** [comment]
好的，感谢反馈，更新了[v216](https://raw.githubusercontent.com/lingeringsound/10007/main/module/ads216.zip)，你试试。

**Comment by AsuraArthur** [comment]
> 好的，感谢反馈，更新了[v216](https://raw.githubusercontent.com/lingeringsound/10007/main/module/ads216.zip)，你试试。

仍然不行。

**Comment by lingeringsound** [comment]
>好的，终端输入命令，截图给我看看，我这边是没问题的。

```
su -c /system/etc/hosts | grep 'wxs.qq.com'
```

```
su -c iptables -L | grep 'wxs.qq.com'
```

----
> ![Screenshot_2024-12-06-17-00-23-556_com.tencent.mm.jpg](https://github.com/user-attachments/assets/eacd93f3-d324-4ce8-b78d-c8d38e749001)

----

**Comment by AsuraArthur** [comment]
> > 好了，输入命令，给我看看，我的截图是没问题的。
> 
> ```
> su -c cat /system/etc/hosts | grep 'wxs.qq.com'
> ```
> 
> ```
> su -c iptables -L | grep 'wxs.qq.com'
> ```
> 
> > ![Screenshot_2024-12-06-17-00-23-556_com.tencent.mm.jpg](https://private-user-images.githubusercontent.com/114198798/393177057-eacd93f3-d324-4ce8-b78d-c8d38e749001.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzYyMzQsIm5iZiI6MTczMzQ3NTkzNCwicGF0aCI6Ii8xMTQxOTg3OTgvMzkzMTc3MDU3LWVhY2Q5M2YzLWQzMjQtNGNlOC1iNzhkLWM4ZDM4ZTc0OTAwMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwOTA1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDFhNjU5YjEwYTNmZDU3YzU4MWE5YzA2MGQxYzVjODczODJiY2RmY2VmYzYyMGQ1ZTFmNDYxNzk1ZGNiNjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1OWzjtuo7XyWZ-TjhgG6Y1aDX4wiwdBILGsRFYdbCPU)

![Uploading Screenshot_2024-12-06-17-14-45-95_9e8df3d0c7c1f50248b6ee043a653d26.jpg…]()

**Comment by AsuraArthur** [comment]
> > 好了，输入命令，给我看看，我的截图是没问题的。
> 
> ```
> su -c cat /system/etc/hosts | grep 'wxs.qq.com'
> ```
> 
> ```
> su -c iptables -L | grep 'wxs.qq.com'
> ```
> 
> > ![Screenshot_2024-12-06-17-00-23-556_com.tencent.mm.jpg](https://private-user-images.githubusercontent.com/114198798/393177057-eacd93f3-d324-4ce8-b78d-c8d38e749001.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzcxMzcsIm5iZiI6MTczMzQ3NjgzNywicGF0aCI6Ii8xMTQxOTg3OTgvMzkzMTc3MDU3LWVhY2Q5M2YzLWQzMjQtNGNlOC1iNzhkLWM4ZDM4ZTc0OTAwMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwOTIwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGJhN2M1YmYyYWEyNDczMTdhNjhhZDVlNjE2NTFkYjFhNTIyYzBmN2ZmNGMwMmFkZjdlZjQ5MmUyMzg2NGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8yU_JADUZp6aZxFpXvP5dVpnULhvIXmzu9OeHnyg7Go)
![Screenshot_2024-12-06-17-14-45-95_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/user-attachments/assets/7ad7cec6-cb1b-4c12-a6cd-b7afa9182ad9)

**Comment by AsuraArthur** [comment]
> iptables拦截了，你重新执行`/data/adb/modules/GGAT_10007/action.sh`(root执行)，输出下面这个命令没结果才是放行。
> 
> ```
> su -c iptables -L | grep 'wxs.qq.com'
> ```
> 
> > 
> 
> ![Screenshot_2024-12-06-17-25-36-754-edit_bin mt plus](https://private-user-images.githubusercontent.com/114198798/393184484-84256dc4-191f-42fa-aee5-99a213c61175.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Nzc1NzMsIm5iZiI6MTczMzQ3NzI3MywicGF0aCI6Ii8xMTQxOTg3OTgvMzkzMTg0NDg0LTg0MjU2ZGM0LTE5MWYtNDJmYS1hZWU1LTk5YTIxM2M2MTE3NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwOTI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODNjMzBkZWI5YzU2MGRlNWZhNzI3Zjg0MGE4ODJmMzMyNDc3NTk3YmUzZDAxNTJhODlhZmMzZWVlZGU5YzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._QH9_0clJHdDFcvgEiWR5gNlrWa-0AbtdnnukjPGfOk)



> iptables拦截了，你重新执行`/data/adb/modules/GGAT_10007/action.sh`(root执行)，输出下面这个命令没结果才是放行。
> 
> ```
> su -c iptables -L | grep 'wxs.qq.com'
> ```
> 
> > 
> 
> ![Screenshot_2024-12-06-17-25-36-754-edit_bin mt plus](https://private-user-images.githubusercontent.com/114198798/393184484-84256dc4-191f-42fa-aee5-99a213c61175.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Nzc1NzMsIm5iZiI6MTczMzQ3NzI3MywicGF0aCI6Ii8xMTQxOTg3OTgvMzkzMTg0NDg0LTg0MjU2ZGM0LTE5MWYtNDJmYS1hZWU1LTk5YTIxM2M2MTE3NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwOTI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODNjMzBkZWI5YzU2MGRlNWZhNzI3Zjg0MGE4ODJmMzMyNDc3NTk3YmUzZDAxNTJhODlhZmMzZWVlZGU5YzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._QH9_0clJHdDFcvgEiWR5gNlrWa-0AbtdnnukjPGfOk)

执行了action.sh文件之后，输出su -c iptables -L | grep 'wxs.qq.com'命令有结果，

再执行文件，输出命令仍然有结果

**Comment by lingeringsound** [comment]
编辑 `/data/adb/modules/GGAT_10007/mod/ad_reward_2.sh`

把`Switch_ad_reward`改成`Switch_ad_reward "allow"`然后执行呢？

**Comment by AsuraArthur** [comment]
ad_reward_2.sh执行了一次，执行了action.sh文件之后，输出su -c iptables -L | grep 'wxs.qq.com'命令有结果，

再执行文件，输出命令仍然有结果....

**Comment by lingeringsound** [comment]
> ad_reward_2.sh执行了一次，执行了action.sh文件之后，输出su -c iptables -L | grep 'wxs.qq.com'命令有结果，
> 
> 再执行文件，输出命令仍然有结果....

- 不知道你是什么情况，你自己执行脚本，截图给我看看，另外你后面发的图，我也没看到。

```
su -c 'iptables -D OUTPUT -m string --string "wxa.wxs.qq.com" --algo bm --to 65535 -j DROP'
su -c 'iptables -D OUTPUT -m string --string "wximg.wxs.qq.com" --algo bm --to 65535 -j DROP'
su -c 'iptables -D OUTPUT -m string --string "wxsmw.wxs.qq.com" --algo bm --to 65535 -j DROP'
```

**Comment by AsuraArthur** [comment]
> > ad_reward_2.sh执行了一次，执行了action.sh文件之后，输出su -c iptables -L | ad_reward_2.sh grep 'wxs.qq.com'命令有结果，
> > 再执行文件，输出命令仍然有结果....
> 
> * 不知道你是什么情况，你自己执行剧本，截图给我看看，另外你后面发的图，我也没看到。
> 
> ```
> su -c 'iptables -D OUTPUT -m string --string "wxa.wxs.qq.com" --algo bm --to 65535 -j DROP'
> su -c 'iptables -D OUTPUT -m string --string "wximg.wxs.qq.com" --algo bm --to 65535 -j DROP'
> su -c 'iptables -D OUTPUT -m string --string "wxsmw.wxs.qq.com" --algo bm --to 65535 -j DROP'
> ```

su -c 'iptables -D OUTPUT -m string --string "wxa.wxs.qq.com" --algo bm --to 65535 -j DROP'
su -c 'iptables -D OUTPUT -m string --string "wximg.wxs.qq.com" --algo bm --to 65535 -j DROP'
su -c 'iptables -D OUTPUT -m string --string "wxsmw.wxs.qq.com" --algo bm --to 65535 -j DROP'
执行以上指令，截图
![Screenshot_2024-12-06-17-56-02-27_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/user-attachments/assets/965ecc3b-0690-4ce2-a2a9-ae7295b1b49e)

**Comment by lingeringsound** [comment]
我的意思是，复制命令，新建一个脚本文件`1.sh`，粘贴命令，root执行脚本文件`1.sh`，然后截图给我。

**Comment by AsuraArthur** [comment]
> 我的意思是，复制命令，创建一个脚本文件`1.sh`，粘贴命令，root执行脚本文件`1.sh`，然后截图给我。

晕，现在可以了，脚本文件执行没有成功....

**Comment by lingeringsound** [comment]
> > 我的意思是，复制命令，创建一个脚本文件`1.sh`，粘贴命令，root执行脚本文件`1.sh`，然后截图给我。
> 
> 晕，现在可以了，脚本文件执行没有成功....

重启还是会出现问题的，不清楚你的环境是啥，按道理直接执行脚本就能解决。
