### ISSUE TITLE
开启模块后，网易云云音乐听歌不计入时长

### ISSUE THREAD

**Issue by Akame828** [lingeringsound/10007#29]
v217版本

将adaway app和此模块同时开启后，将adaway关闭并重启手机可解决网易云音乐听歌不计入听歌时长的问题。
请问是有什么host影响了网易云的此功能？

**Comment by lingeringsound** [comment]
好的，感谢反馈，但是我的网易云已经好久没上了，听歌时长在哪看😭？

**Comment by Akame828** [comment]
> ？

![Screenshot_2024-12-11-19-07-00-534_com.netease.cloudmusic-edit.jpg](https://github.com/user-attachments/assets/23f2e8e2-1488-4a4e-bcf0-133f852f995f)

也可以直接搜听歌足迹

**Comment by Akame828** [comment]
> 好的，感谢反馈，但是我的网易云已经好久没上了，听歌时长在哪看😭？

![Screenshot_2024-12-11-19-07-00-534_com.netease.cloudmusic-edit.jpg](https://github.com/user-attachments/assets/64c6041e-fee9-4e87-82f0-f48b133bd254)

也可以直接搜听歌足迹

**Comment by lingeringsound** [comment]
---
> ![Screenshot_2024-12-11-19-31-26-101-edit_com.netease.cloudmusic.jpg](https://github.com/user-attachments/assets/c70a3e21-3b12-4f8c-9168-881abe993cd4)

---

旧版本没找到这个玩意，刚刚听了几首歌没记录，然后放行了底下的域名就有记录了，你可以试试。

```
#网易云音乐听歌统计
clientlog3.music.163.com
```

**Comment by Akame828** [comment]
> #网易云音乐听歌统计
> clientlog3.music.163.com

可以了大佬，另外我想问一下一个软件没有实现去广的功能，是要添加那个软件的广告的域名到自定义host里边吗？域名应该如何获取？

**Comment by lingeringsound** [comment]
抓包(httpCanary/ProxyPin)，或者用`Adguard`/`Adaway`之类的软件，看网络日志，然后自己把域名放到黑名单/用户拦截规则，不过现在dns过滤广告本来就没多少用了，流氓广告基本都是混用域名的，需要重写或者https过滤，还是建议找找xposed模块实现吧，
