### ISSUE TITLE
adaway+完整版hosts文件订阅可以屏蔽开屏广告，只刷模块166启用hosts也无法屏蔽

### ISSUE THREAD

**Issue by ou7yang** [lingeringsound/10007#3]
主要是指小绿书，adaway+完整版hosts文件订阅可以屏蔽开屏广告，但关掉adawsy后，只刷模块166，即使启用hosts也无法屏蔽，不懂哪里有问题

**Comment by lingeringsound** [comment]
Adaway修改了hosts，模块也修改了hosts，关闭Adaway时会复原hosts文件，而模块无法再次修改hosts文件，Adaway覆盖了模块的hosts。

并且这两个用起来并不冲突。

**Comment by ou7yang** [comment]
> Adaway修改了hosts，模块也修改了hosts，关闭Adaway时会复原hosts文件，而模块无法再次修改hosts文件，Adaway覆盖了模块的hosts。
> 
> 并且这两个用起来并不冲突。

如果是这样的话，重刷一遍模块应该可以解决？打算试试看，如果可用的话就卸载掉adaway了
