### ISSUE TITLE
kernelSU安装导致卡开机页面

### ISSUE THREAD

**Issue by EndesrDragons** [lingeringsound/10007#30]
从219开始，在ksu里更新安装之后，重启卡一次logo，再长按关机键重启就好了，这是因为什么导致的

**Comment by EndesrDragons** [comment]
kernelSU版本1.0.2

**Comment by lingeringsound** [comment]
- 换`overlay`挂载了，话说就没人看下`README.md`或者更新日志吗？
> 我不用 `kernel su`，所以你自己测试一下，看看这个还卡不卡开机。

[ads221.zip](https://github.com/user-attachments/files/18105991/ads221.zip)

**Comment by EndesrDragons** [comment]
> - 换`overlay`挂载了，话说就没人看下`README.md`或者更新日志吗？
> > 我不用 `kernel su`，所以你自己测试一下，看看这个还卡不卡开机。
> 
> [ads221.zip](https://github.com/user-attachments/files/18105991/ads221.zip)
> 
> 

每次更新完我都看的，主要是没明白这个加载是什么意思

**Comment by EndesrDragons** [comment]
> - 换`overlay`挂载了，话说就没人看下`README.md`或者更新日志吗？
> > 我不用 `kernel su`，所以你自己测试一下，看看这个还卡不卡开机。
> 
> [ads221.zip](https://github.com/user-attachments/files/18105991/ads221.zip)
> 
> 

好了，这次没卡开机页面了，感谢大佬

**Comment by lingeringsound** [comment]
- [抄的模块](https://github.com/symbuzzer/systemless-hosts-KernelSU-module)
- [overlay-fs](https://bing.com/search?q=overlay-fs%20mount%E5%91%BD%E4%BB%A4)

**Comment by lingeringsound** [comment]
> > * 换`overlay`挂载了，话说就没人看下`README.md`或者更新日志吗？
> > 
> > > 我不用 `kernel su`，所以你自己测试一下，看看这个还卡不卡开机。
> > 
> > 
> > [ads221.zip](https://github.com/user-attachments/files/18105991/ads221.zip)
> 
> 好了，这次没卡开机页面了，感谢大佬

- **不客气**
