### ISSUE TITLE
[Bug]KernelSU hosts替换失效

### ISSUE THREAD

**Issue by yuexps** [lingeringsound/10007#31]
貌似KernelSU的hosts替换失效了，多次测试，重新刷入重启后，hosts并没有被替换。
![Screenshot_2024-12-13-12-28-54-963_bin mt plus](https://github.com/user-attachments/assets/0a86c96f-c5e8-46ee-bb19-93147ce0fd83)
![Screenshot_2024-12-13-12-29-04-461_me weishu kernelsu](https://github.com/user-attachments/assets/3d4ae10d-572b-40f9-ad44-893cca7e1188)

**Comment by lingeringsound** [comment]
`kernel su`真麻烦啊，在`/data/adb/modules/GGAT_10007`创建一个脚本`0.sh`，输入代码，Root执行，提示什么报错？

```

#!/system/bin/sh
MODDIR=${0%/*}
BUSYBOXDIR=$MODDIR/busybox
export PATH=/system/bin:$BUSYBOXDIR:$PATH

if test -d "$MODDIR/worker" ;then
	modules_host="$(find "${MODDIR}" -iname 'hosts' -type f | head -n 1)"
	modules_host_folder="${modules_host%/*}"
if test "${modules_host_folder}" = "" ;then
		echo "[!] hosts文件丢失！"
else
		system_hosts="$(echo "${modules_host}" | sed "s|${MODDIR}||g")"
			system_hosts_folder="${system_hosts%/*}"
  echo -e "\n模块hosts路径: ${modules_host_folder}\n系统hosts路径:${system_hosts_folder}\n"

		mount -t overlay -o lowerdir=${modules_host_folder},upperdir=${system_hosts_folder},workdir=$MODDIR/worker KSU ${system_hosts_folder}
	fi
fi
```

**Comment by yuexps** [comment]
> `kernel su`真麻烦啊，在`/data/adb/modules/GGAT_10007`创建一个脚本`0.sh`，输入代码，Root执行，提示什么报错？
> 
> ```
> 
> #!/system/bin/sh
> MODDIR=${0%/*}
> BUSYBOXDIR=$MODDIR/busybox
> export PATH=/system/bin:$BUSYBOXDIR:$PATH
> 
> if test -d "$MODDIR/worker" ;then
> 	modules_host="$(find "${MODDIR}" -iname 'hosts' -type f | head -n 1)"
> 	modules_host_folder="${modules_host%/*}"
> if test "${modules_host_folder}" = "" ;then
> 		echo "[!] hosts文件丢失！"
> else
> 		system_hosts="$(echo "${modules_host}" | sed "s|${MODDIR}||g")"
> 			system_hosts_folder="${system_hosts%/*}"
>   echo -e "\n模块hosts路径: ${modules_host_folder}\n系统hosts路径:${system_hosts_folder}\n"
> 
> 		mount -t overlay -o lowerdir=${modules_host_folder},upperdir=${system_hosts_folder},workdir=$MODDIR/worker KSU ${system_hosts_folder}
> 	fi
> fi
> ```


mount: 'KSU'->'/system/etc': Invalid argument![Screenshot_2024-12-13-12-54-19-115_bin mt plus](https://github.com/user-attachments/assets/9c9b3df1-6578-4fbf-a8f8-540b9e0e1dad)

**Comment by lingeringsound** [comment]
把`KSU`删除呢？保留`${system_hosts_folder}`

**Comment by lingeringsound** [comment]
不行的话，还是换成`mount --bind`算了( ๑ŏ ﹏ ŏ๑ )

**Comment by yuexps** [comment]
> 把`KSU`删除呢？保留`${system_hosts_folder}`

![Screenshot_2024-12-13-13-00-16-664_bin mt plus](https://github.com/user-attachments/assets/682fa1cd-13d3-4ebe-b7e1-b2c7bd954c5c)
![Screenshot_2024-12-13-13-00-01-344_bin mt plus](https://github.com/user-attachments/assets/200f01e8-a863-4c77-a383-f25c552f4e4d)

**Comment by yuexps** [comment]
> 不行的话，还是换成`mount --bind`算了( ๑ŏ ﹏ ŏ๑ )

![Screenshot_2024-12-13-13-07-29-437_bin mt plus](https://github.com/user-attachments/assets/6bd06d10-6ad6-4dde-896e-0057cadc07ec)
worker里是空的

**Comment by yuexps** [comment]
> 不行的话，还是换成`mount --bind`算了( ๑ŏ ﹏ ŏ๑ )

![Screenshot_2024-12-13-13-10-41-069_bin mt plus](https://github.com/user-attachments/assets/0e7d3f5b-7166-425a-9914-ccffacc1b7bb)
![Uploading Screenshot_2024-12-13-13-10-13-218_bin.mt.plus.png…]()

**Comment by yuexps** [comment]
![Screenshot_2024-12-13-13-10-13-218_bin mt plus](https://github.com/user-attachments/assets/cdb355d4-0cb4-4d17-a9c9-27a5c743600e)
