### ISSUE TITLE
请求添加拦截埋堆堆（一个看港剧的app）广告，谢谢

### ISSUE THREAD

**Issue by samsunggithub** [lingeringsound/10007#33]
如题，抓包手动添加以下两项后，可屏蔽此app广告（如图），方便的话麻烦添加上去，谢谢。
sdk-data.ubixioe.com
tower.ubixioe.com
![1](https://github.com/user-attachments/assets/dacde94c-3e91-417c-94b6-426bd47b45c5)

**Comment by lingeringsound** [comment]
好的，感谢反馈，你可以加在模块的`自定义.prop`中，重新刷入添加。

**Comment by lingeringsound** [comment]
你说的埋堆堆是`com.tvbc.maiduidui`，这个埋堆堆吧说实话，等了很久也没抓到上面那个域名😢，不过在GIthub上找到其他大佬抓的的，我先加进去。
- 我清楚了几次数据，只有一个开屏广告，混用域名的，里面的几个域名我感觉都是混用的。
```
https://mob.mddcloud.com.cn/adApi/advert/
firstpart/advertList
```

**Comment by samsunggithub** [comment]
> 好的，感谢反馈，你可以加在模块的`自定义.prop`中，重新刷入添加。

已加进去。之前我一直都是拦截这俩个，然后开屏和播放暂停、还有app内的广告都没了，最近换了您这款模块就没拦截到，然后才过来反馈的，麻烦您了。暂时清净了，再次感谢。

**Comment by samsunggithub** [comment]
> https://mob.mddcloud.com.cn/adApi/advert/
> firstpart/advertList

是的，就是这个埋堆堆com.tvbc.maiduidui。
