### ISSUE TITLE
删除困难

### ISSUE THREAD

**Issue by derek565** [lingeringsound/10007#4]
感觉模块会影响一些正常操作，例如番茄小说无法通过抖音登录，删除了模块后，依旧不行，可能没有彻底卸载或hosts文件没有改过来

**Comment by lingeringsound** [comment]
所以我说过，尽量不要用模块，直接用`Adaway`之类的，用订阅，而不是模块，因为你不清楚模块做了什么，就不要用它，否则就是在养蛊。

**Comment by lingeringsound** [comment]
另外，手机使用环境不同，我也没办法复现问题，毕竟我这边是正常登陆的。

**Comment by lingeringsound** [comment]
最简单就是卸载重装。

**Comment by lingeringsound** [comment]
这两个软件都有云同步，清除数据，不影响。

**Comment by lingeringsound** [comment]
下载一个 [Adaway](https://github.com/AdAway/AdAway) ，刷入magisk的或者ksu的systemless hosts模块，重启，然后在Adaway点击中间的暂停键，这样就会恢复hosts。

或者你自己想办法使得原本的hosts内容为
```
127.0.0.1	localhost
::1	localhost
```
路径在/system/etc/hosts

**Comment by lingeringsound** [comment]
magisk自带hosts模块，ksu可以用这个 https://github.com/symbuzzer/systemless-hosts-KernelSU-module

**Comment by lingeringsound** [comment]
hosts文件内容只保留这点玩意就够了
```
127.0.0.1	localhost
::1	localhost
```
