### ISSUE TITLE
模块对mipush可能存在影响

### ISSUE THREAD

**Issue by Stop-586** [lingeringsound/10007#5]
首先，模块非常好，这毋庸置疑。

我是从167版本开始使用的，167-170版本对小米云端推送的影响不是很大，从174和175开始，就明显感知有影响了。

即时通讯的mipush是正常的，系统层mipush是正常的。但对除NTQQ以外的，其他已接入mipush的应用，有主要表现为推送减少或不推送的情况。

模块不是万能的，我非常理解，只是简单反馈一下。非常谢谢作者。

**Comment by lingeringsound** [comment]
我再检查一下吧，这个我放行过很多次了，有的人没问题，有的人会出现这种情况，我自己也是MIUI，但是没碰到过，不知道怎么复现。

**Comment by Stop-586** [comment]
180版本体验非常好，虽然不知道作者做了什么微调整，但之前本机在173到179版本的三方app(非即时通讯app)，mipush推送减少或无法推送的问题，得到明显缓解。具体表现为每日推送条数增加，感知通畅，原先没有推送的三方app，每天也有一到两天条推送，且去广告能力保持不变。

根据我的使用经验，告诉一些与本机情况相同的用户，在影响mipush推送时，退回到你认为推送正常的去广告版本，而后删除出现推送异常的目标应用，重新安装即可。对于mipush推送问题，去广告模块的每个版本对应每个机型的情况也许有所不同，待在你认可的版本使用视为最优解。还是那句话，模块刷入后是机械的，没有主观能动性的，要结合作者每个版本的调整，自己琢磨着选出适合自己的去广告模块版本。

模块是好模块，感谢作者的付出。
