### ISSUE TITLE
部分游戏奖励广告被误杀

### ISSUE THREAD

**Issue by luqin2007** [lingeringsound/10007#6]
奖励广告配置为否（默认），以下游戏的广告被误杀：
喵喵妙妙塔：数涂
小小法师
橡子屋

**Comment by lingeringsound** [comment]
那就不建议用模块，用[Adaway](https://github.com/AdAway/AdAway)吧，毕竟不可能100%识别到广告奖励，而且放行了奖励，还可能会使得其他开屏广告出现。

**Comment by luiqn2007** [comment]
ok
