### ISSUE TITLE
crond任务管理

### ISSUE THREAD

**Issue by pzh15376** [lingeringsound/10007#7]
大佬能不能补发一下，原先的链接已经没了，辛苦大佬了

**Comment by lingeringsound** [comment]
[Crond任务管理_0.20beta.zip](https://github.com/user-attachments/files/17485976/Crond._0.20beta.zip)

**Comment by lingeringsound** [comment]
[Crond任务管理_0.20beta_sign.zip](https://github.com/user-attachments/files/17486009/Crond._0.20beta_sign.zip)
