### ISSUE TITLE
小米云服务->云备份挂掉了

### ISSUE THREAD

**Issue by scwlwj** [lingeringsound/10007#9]
v183。小米云服务->云备份 会挂掉，同步不了。卸载以后可以正常备份。
期望将云相关的hosts去掉

**Comment by scwlwj** [comment]
桌面备份不了，但应用数据云同步还是可以的

**Comment by lingeringsound** [comment]
好的，感谢反馈，但是我不用云备份，抓不到，不清楚是哪个域名(~~之前已经放行过一堆域名~~)，我也蹲一个列表。

**Comment by lingeringsound** [comment]
好像找到了`a0.app.xiaomi.com` [链接](https://github.com/TG-Twilight/AWAvenue-Ads-Rule/issues/38#issue-2152335666)
@TG-Twilight/AWAvenue-Ads-Rule#38

**Comment by scwlwj** [comment]
辛苦了，刚看到回复
